export const themePresets = {
    default: {
        name: 'Default',
        category: 'light',
        animation: 'float',
        particleColor: 'rgba(59, 130, 246, 0.4)',
        particleType: 'dots',
        light: {
            background: "#FFFFFF",  // Clean white for reading
            card: "#F8FAFC",
            primary: "#2563EB",
            secondary: "#E5E7EB",
            textPrimary: "#1F2937",
            textSecondary: "#6B7280",
            border: "#E5E7EB",
            accent: "#3B82F6",
            surface: "#FFFFFF",
        },
        dark: {
            background: "#0F172A",
            card: "#1E293B",
            primary: "#3B82F6",
            secondary: "#334155",
            textPrimary: "#F8FAFC",
            textSecondary: "#94A3B8",
            border: "#334155",
            accent: "#60A5FA",
            surface: "#1E293B",
        },
    },
    ocean: {
        name: 'Ocean',
        category: 'premium-dark',
        animation: 'wave',
        particleColor: 'rgba(34, 211, 238, 0.5)',
        particleType: 'bubbles',
        waveSpeed: 1.5,
        light: {
            background: "#FFFFFF",  // Clean white for reading
            card: "#F8FAFC",
            primary: "#38BDF8",
            secondary: "#2DD4BF",
            textPrimary: "#0F172A",
            textSecondary: "#475569",
            border: "#E5E7EB",
            accent: "#06B6D4",
            surface: "#FFFFFF",
        },
        dark: {
            background: "#020617",
            card: "#0F172A",
            primary: "#38BDF8",
            secondary: "#2DD4BF",
            textPrimary: "#E0F2FE",
            textSecondary: "#7DD3FC",
            border: "#1E293B",
            accent: "#22D3EE",
            surface: "#0F172A",
        },
    },
    forest: {
        name: 'Forest',
        category: 'premium-dark',
        animation: 'drift',
        particleColor: 'rgba(34, 197, 94, 0.4)',
        particleType: 'leaves',
        light: {
            background: "#FFFFFF",  // Clean white for reading
            card: "#F8FAFC",
            primary: "#22C55E",
            secondary: "#84CC16",
            textPrimary: "#064E3B",
            textSecondary: "#166534",
            border: "#E5E7EB",
            accent: "#4ADE80",
            surface: "#FFFFFF",
        },
        dark: {
            background: "#022C22",
            card: "#064E3B",
            primary: "#22C55E",
            secondary: "#84CC16",
            textPrimary: "#ECFDF5",
            textSecondary: "#6EE7B7",
            border: "#065F46",
            accent: "#4ADE80",
            surface: "#064E3B",
        },
    },
    sunset: {
        name: 'Sunset',
        category: 'premium-dark',
        animation: 'pulse',
        particleColor: 'rgba(251, 146, 60, 0.5)',
        particleType: 'orbs',
        light: {
            background: "#FFFFFF",  // Clean white for reading
            card: "#F8FAFC",
            primary: "#FB923C",
            secondary: "#F472B6",
            textPrimary: "#7C2D12",
            textSecondary: "#9F1239",
            border: "#E5E7EB",
            accent: "#F97316",
            surface: "#FFFFFF",
        },
        dark: {
            background: "#1E1B4B",
            card: "#312E81",
            primary: "#FB923C",
            secondary: "#F472B6",
            textPrimary: "#FDF2F8",
            textSecondary: "#FBCFE8",
            border: "#3730A3",
            accent: "#F97316",
            surface: "#312E81",
        },
    },
    neon: {
        name: 'Neon',
        category: 'premium-dark',
        animation: 'glow',
        particleColor: 'rgba(168, 85, 247, 0.6)',
        particleType: 'electric',
        light: {
            background: "#FFFFFF",  // Clean white for reading
            card: "#F8FAFC",
            primary: "#A855F7",
            secondary: "#22D3EE",
            textPrimary: "#1E1B4B",
            textSecondary: "#4C1D95",
            border: "#E5E7EB",
            accent: "#0EA5E9",
            surface: "#FFFFFF",
        },
        dark: {
            background: "#020617",
            card: "#111827",
            primary: "#A855F7",
            secondary: "#22D3EE",
            textPrimary: "#F5F3FF",
            textSecondary: "#C4B5FD",
            border: "#1F2933",
            accent: "#38BDF8",
            surface: "#111827",
        },
    },
};
